#Lab1
Create an inventory file under ~/playbooks directory on Ansible controller host and add web1 as managed node. IP address of web1 node is 172.20.1.100, SSH user is root and password is Passw0rd.
Create a playbook ~/playbooks/zip.yml to make a zip archive opt.zip of /opt directory on web1 node and save it under /root on web1 node itself.
inventory.yml
web1 ansible_host=172.20.1.100 ansible_ssh_pass=Passw0rd ansible_user=root
~/playbooks/zip.yml
---
- name: Zip archive opt.zip
  hosts: web1
  tasks:
   - archive:
       path: /opt
       dest: /root/opt.zip
       format: zip

#Lab2
On Ansible controller we have a zip archive local.zip. We want to extract its contents on web1 under /tmp directory. Create a playbook local.yml under ~/playbooks to complete the task.
---
- name: extract filesystem
  hosts: web1 
  tasks:
  - unarchive:
      src: local.zip
      dest: /tmp
   



#Lab3:
On web1 node we have an archive data.tar.gz under /root directory, extract it under /srv directory by developing a playbook ~/playbooks/data.yml and make sure data.tar.gz archive is removed after that.

---
- name: extract file
  hosts: web1
  tasks:
  - unarchive:
      src: /root/data.tar.gz
      dest: /srv
      remove: yes 

- name: Extract data.tar.gz on web1
  hosts: web1
  tasks:
  - unarchive:
      src: /root/data.tar.gz
      dest: /srv
      remote_src: yes

  - file: path=/root/data.tar.gz state=absent


#Lab4

Create a playbook download.yml under ~/playbooks to download and extract https://github.com/kodekloudhub/Hello-World/archive/master.zip zip archive under /root directory on web1 node.
- name: Download and extract from URL
  hosts: web1
  tasks:
  -   unarchive:
       src: https://github.com/kodekloudhub/Hello-World/archive/master.zip
       dest: /root
       remote_src: yes



#Lab5
We have three files on web1 node /root/file1.txt, /usr/local/share/file2.txt and /var/log/lastlog. Create a bz2 archive of all these files and save it under /root, name the archive as files.tar.bz2. You can create ~/playbooks/files.yml playbook for it.

- name: Compress multiple files
  hosts: web1
  tasks:
  - archive:
     path:
      - /root/file1.txt
      - /usr/local/share/file2.txt
      - /var/log/lastlog
     dest: /root/files.tar.bz2
     format: bz2

#Lab6We want to setup nginx on web1 node with some sample html code. Create a playbook ~/playbooks/nginx.yml to do so. Below are the details about the task:


a. Install nginx package and start/enable its service.

b. Extract /root/nginx.zip archive under /usr/share/nginx/html directory.

c. Inside /usr/share/nginx/html/index.html replace line This is sample html code with line This is KodeKloud Ansible lab.

- name: Install and configure nginx on web1
  hosts: web1
  tasks:
   - name: Install nginx
     yum: 
     name: nginx 
     state: installed
   - name: Start nginx
     service:
     name: nginx 
     state: started
     enabled: yes

  - name: Extract nginx.zip
    unarchive:
     src=/root/nginx.zip dest=/usr/share/nginx/html remote_src=yes

  - name: Replace line in index.html
    replace:
     path: /usr/share/nginx/html/index.html
     regexp: This is sample html code
     replace: This is KodeKloud Ansible lab
